using AiMeetingAssistant.Core.Transcripts;
namespace AiMeetingAssistant.Core.Storage;
public sealed record SessionStorageEntry(string SessionDirectory,string SessionName,DateTimeOffset Modified,long CaptureBytes,long TranscriptBytes,long ProcessingBytes,long TotalBytes,string ArchiveStatus,long ReclaimableBytes,string ArchiveAction){public string ModifiedLabel=>Modified.ToLocalTime().ToString("g");public string CaptureLabel=>StorageInventory.Format(CaptureBytes);public string TranscriptLabel=>StorageInventory.Format(TranscriptBytes);public string ProcessingLabel=>StorageInventory.Format(ProcessingBytes);public string TotalLabel=>StorageInventory.Format(TotalBytes);public string ReclaimableLabel=>StorageInventory.Format(ReclaimableBytes);}
public sealed record StorageInventoryReport(string Root,long FreeBytes,long LibraryBytes,long CaptureBytes,long TranscriptBytes,long ProcessingBytes,IReadOnlyList<SessionStorageEntry> Sessions){public string FreeLabel=>StorageInventory.Format(FreeBytes);public string LibraryLabel=>StorageInventory.Format(LibraryBytes);public string CaptureLabel=>StorageInventory.Format(CaptureBytes);public string TranscriptLabel=>StorageInventory.Format(TranscriptBytes);public string ProcessingLabel=>StorageInventory.Format(ProcessingBytes);public string CapacityLabel=>$"Approx. {FreeBytes/(40d*1024*1024*60):0.0} recording hour(s)";}
public static class StorageInventory
{
 public static StorageInventoryReport Scan(string rootPath){var root=Path.GetFullPath(rootPath);Directory.CreateDirectory(root);var drive=new DriveInfo(Path.GetPathRoot(root)!);var sessions=new List<SessionStorageEntry>();foreach(var dir in Directory.EnumerateDirectories(root,"session_*")){long capture=0,transcript=0,processing=0;foreach(var file in Directory.EnumerateFiles(dir,"*",SearchOption.AllDirectories)){long size;try{size=new FileInfo(file).Length;}catch{continue;}var rel=Path.GetRelativePath(dir,file);if(!rel.StartsWith("processing"+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))capture+=size;else if(Path.GetFileName(file).StartsWith("transcript",StringComparison.OrdinalIgnoreCase)||file.EndsWith("speaker-names.json",StringComparison.OrdinalIgnoreCase))transcript+=size;else processing+=size;}var sources=SessionAudioSourceResolver.Resolve(dir);var removal=PcmMasterRemoval.Preview(dir);var archived=sources.Count==2&&sources.All(x=>x.UsesArchive);var wav=Directory.EnumerateFiles(dir,"*.wav",SearchOption.TopDirectoryOnly).Any();var status=archived?(wav?(removal.Candidates.Count>0?"FLAC proven":"FLAC available"):"Archived · FLAC only"):"WAV only";var action=removal.Candidates.Count>0?"WAV can be removed":removal.BlockReason??"Create verified FLAC";sessions.Add(new(dir,Path.GetFileName(dir),Directory.GetLastWriteTimeUtc(dir),capture,transcript,processing,capture+transcript+processing,status,removal.ReclaimableBytes,action));}var list=sessions.OrderByDescending(x=>x.TotalBytes).ToArray();return new(root,drive.AvailableFreeSpace,list.Sum(x=>x.TotalBytes),list.Sum(x=>x.CaptureBytes),list.Sum(x=>x.TranscriptBytes),list.Sum(x=>x.ProcessingBytes),list);}
 public static string Format(long value){string[] units=["B","KB","MB","GB","TB"];var size=(double)Math.Max(0,value);var i=0;while(size>=1024&&i<units.Length-1){size/=1024;i++;}return $"{size:0.0} {units[i]}";}
}
