using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Text.Json;
using AiMeetingAssistant.Windows.Worker;
using Microsoft.Win32;
namespace AiMeetingAssistant.Desktop;
public partial class SettingsWindow : Window
{
    private readonly AppSettings _original=AppPreferences.Load();
    private Process? _speechModelProcess;private bool _cancelRequested;
    public SettingsWindow(){InitializeComponent();Closing+=OnClosing;ScreenCaptureCheckBox.IsChecked=_original.ScreenCaptureEnabled;CaptureDirectoryTextBox.Text=_original.CaptureDirectory;ModelDirectoryTextBox.Text=_original.ModelDirectory??"";RefreshSpeechModels(_original.SpeechModelId);ComputeComboBox.ItemsSource=new[]{new Choice("Automatic","automatic"),new Choice("CPU only","cpu-only"),new Choice("Prefer NVIDIA CUDA (fallback to CPU)","prefer-cuda"),new Choice("Intel GPU (OpenVINO · Whisper Small)","intel-gpu")};ComputeComboBox.SelectedValue=_original.ComputePreference;SettingsPathText.Text=$"Settings file: {AppPreferences.FilePath}";IntelStatusText.Text=GetIntelStatus();}
    private static string GetIntelStatus(){var runtime=LocalModelResolver.ResolveOpenVinoRuntime();var model=LocalModelResolver.ResolveOpenVinoSpeechModel("small");return runtime is not null&&model is not null?$"Ready · Intel runtime and Whisper Small model detected\n{model}":$"Not ready · {(runtime is null?"OpenVINO runtime missing":"runtime installed")} · {(model is null?"Intel Whisper Small model missing":"model installed")}";}
    private void RefreshSpeechModels(string? selectedId){SpeechModelComboBox.ItemsSource=LocalModelResolver.SpeechModels.Select(m=>new SpeechModelChoice(m,LocalModelResolver.IsSpeechModelInstalled(m.Id))).ToArray();SpeechModelComboBox.SelectedValue=selectedId??LocalModelResolver.DefaultSpeechModelId;UpdateSpeechModelDetails();}
    private void OnSpeechModelChanged(object sender,SelectionChangedEventArgs e)=>UpdateSpeechModelDetails();
    private void UpdateSpeechModelDetails(){if(SpeechModelComboBox.SelectedItem is not SpeechModelChoice s)return;SpeechModelStatusText.Text=s.Installed?"Installed · ready to select":"Not installed";SpeechModelStatusText.Foreground=(System.Windows.Media.Brush)FindResource(s.Installed?"AccentBrush":"MutedBrush");SpeechModelDetailText.Text=$"Quality: {s.Quality} · Download: {s.DownloadSize}\n{s.HardwareGuidance}\nLocal folder: {s.DirectoryName}";InstallSpeechModelButton.IsEnabled=!s.Installed&&_speechModelProcess is null;RemoveSpeechModelButton.IsEnabled=s.Installed&&_speechModelProcess is null;}
    private async void OnInstallSpeechModel(object sender,RoutedEventArgs e)=>await RunSpeechModelOperationAsync("install");
    private async void OnRemoveSpeechModel(object sender,RoutedEventArgs e){if(SpeechModelComboBox.SelectedItem is not SpeechModelChoice s)return;if(s.Id==_original.SpeechModelId&&string.IsNullOrWhiteSpace(_original.ModelDirectory)){SpeechModelOperationText.Text="This is the active default model. Select and save another installed model, restart, then remove it.";return;}if(MessageBox.Show(this,$"Remove {s.DisplayName} from this computer?","Remove model",MessageBoxButton.YesNo,MessageBoxImage.Warning)==MessageBoxResult.Yes)await RunSpeechModelOperationAsync("remove");}
    private void OnCancelSpeechModel(object sender,RoutedEventArgs e){_cancelRequested=true;try{if(_speechModelProcess is {HasExited:false})_speechModelProcess.Kill(entireProcessTree:true);}catch{}SpeechModelOperationText.Text="Cancelling model download...";}
    private async Task RunSpeechModelOperationAsync(string operation)
    {
        if(_speechModelProcess is not null||SpeechModelComboBox.SelectedItem is not SpeechModelChoice selected)return;_cancelRequested=false;SetSpeechModelOperationState(true,operation=="install"?$"Downloading {selected.DisplayName}...":$"Removing {selected.DisplayName}...");
        try{var script=FindWorkerFile("manage_speech_model.py");var root=Path.Combine(Path.GetDirectoryName(script)!,"models");var start=new ProcessStartInfo(PythonRuntimeResolver.Resolve()){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};start.ArgumentList.Add(script);start.ArgumentList.Add(operation);start.ArgumentList.Add("--model-id");start.ArgumentList.Add(selected.Id);start.ArgumentList.Add("--models-root");start.ArgumentList.Add(root);using var process=Process.Start(start)??throw new InvalidOperationException("Could not start the model manager.");_speechModelProcess=process;var progress=PumpModelProgressAsync(process.StandardOutput,selected.DisplayName);var error=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();await progress;var stderr=(await error).Trim();if(_cancelRequested)throw new OperationCanceledException();if(process.ExitCode!=0)throw new InvalidOperationException(stderr.Length>0?stderr:"Model operation failed.");SpeechModelOperationText.Text=operation=="install"?$"{selected.DisplayName} installed successfully.":$"{selected.DisplayName} removed.";}
        catch(OperationCanceledException){CleanupPartialInstall(selected.DirectoryName);SpeechModelOperationText.Text="Model download cancelled; partial files were removed.";}catch(Exception exception){SpeechModelOperationText.Text=$"Model operation failed: {exception.Message}";}finally{_speechModelProcess=null;RefreshSpeechModels(selected.Id);SetSpeechModelOperationState(false,SpeechModelOperationText.Text);UpdateSpeechModelDetails();}
    }
    private async Task PumpModelProgressAsync(StreamReader reader,string displayName)
    {
        while(await reader.ReadLineAsync() is { } line)try{using var json=JsonDocument.Parse(line);var root=json.RootElement;if(root.GetProperty("status").GetString()!="progress")continue;var done=root.GetProperty("downloadedBytes").GetInt64();var total=root.GetProperty("totalBytes").GetInt64();var speed=root.GetProperty("bytesPerSecond").GetInt64();SpeechModelProgress.IsIndeterminate=total<=0;SpeechModelProgress.Maximum=Math.Max(total,1);SpeechModelProgress.Value=Math.Min(done,Math.Max(total,1));SpeechModelOperationText.Text=$"Downloading {displayName} · {FormatBytes(done)} / {FormatBytes(total)} · {FormatBytes(speed)}/s";}catch(JsonException){}
    }
    private static string FormatBytes(long value){string[] units=["B","KB","MB","GB"];var size=(double)Math.Max(value,0);var unit=0;while(size>=1024&&unit<units.Length-1){size/=1024;unit++;}return $"{size:0.0} {units[unit]}";}
    private static void CleanupPartialInstall(string directoryName){try{var root=Path.Combine(Path.GetDirectoryName(FindWorkerFile("manage_speech_model.py"))!,"models");if(!Directory.Exists(root))return;foreach(var path in Directory.EnumerateDirectories(root,$".{directoryName}.installing-*",SearchOption.TopDirectoryOnly))Directory.Delete(path,true);}catch{}}
    private void SetSpeechModelOperationState(bool running,string message){SpeechModelOperationText.Text=message;SpeechModelProgress.Visibility=running?Visibility.Visible:Visibility.Collapsed;SpeechModelProgress.IsIndeterminate=running;SpeechModelProgress.Value=0;CancelSpeechModelButton.Visibility=running?Visibility.Visible:Visibility.Collapsed;SpeechModelComboBox.IsEnabled=!running;InstallSpeechModelButton.IsEnabled=!running;RemoveSpeechModelButton.IsEnabled=!running;}
    private void OnClosing(object? sender,System.ComponentModel.CancelEventArgs e){if(_speechModelProcess is not {HasExited:false})return;e.Cancel=true;SpeechModelOperationText.Text="Cancel the model download before closing Settings.";}
    private void OnBrowseCapture(object sender,RoutedEventArgs e){var d=new OpenFolderDialog{InitialDirectory=CaptureDirectoryTextBox.Text};if(d.ShowDialog(this)==true)CaptureDirectoryTextBox.Text=d.FolderName;}
    private void OnBrowseModel(object sender,RoutedEventArgs e){var d=new OpenFolderDialog{InitialDirectory=ModelDirectoryTextBox.Text};if(d.ShowDialog(this)==true)ModelDirectoryTextBox.Text=d.FolderName;}
    private async void OnInstallDiarization(object sender,RoutedEventArgs e)
    {var token=HuggingFaceTokenBox.Password;HuggingFaceTokenBox.Clear();if(!token.StartsWith("hf_",StringComparison.Ordinal)||token.Length<23){DiarizationInstallStatus.Text="Enter the complete token beginning with hf_.";return;}InstallDiarizationButton.IsEnabled=false;DiarizationInstallStatus.Text="Downloading and validating the local diarization model...";try{var script=FindWorkerFile("download_diarization_model.py");var target=Path.Combine(Path.GetDirectoryName(script)!,"models","speaker-diarization-community-1");var start=new ProcessStartInfo(PythonRuntimeResolver.Resolve()){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};start.ArgumentList.Add(script);start.ArgumentList.Add("--target");start.ArgumentList.Add(target);start.Environment["HF_TOKEN"]=token;token=string.Empty;using var process=Process.Start(start)??throw new InvalidOperationException("Could not start the model downloader.");var output=process.StandardOutput.ReadToEndAsync();var error=process.StandardError.ReadToEndAsync();await process.WaitForExitAsync();if(process.ExitCode!=0)throw new InvalidOperationException((await error).Trim());DiarizationInstallStatus.Text=$"Installed locally: {target}";}catch(Exception exception){DiarizationInstallStatus.Text=$"Installation failed: {exception.Message}";}finally{InstallDiarizationButton.IsEnabled=true;}}
    private static string FindWorkerFile(string name){foreach(var start in new[]{Environment.CurrentDirectory,AppContext.BaseDirectory})for(var d=new DirectoryInfo(start);d is not null;d=d.Parent){var candidate=Path.Combine(d.FullName,"worker",name);if(File.Exists(candidate))return candidate;}throw new FileNotFoundException($"Worker installer file not found: {name}");}
    private void OnSave(object sender,RoutedEventArgs e){try{var selected=SpeechModelComboBox.SelectedItem as SpeechModelChoice??throw new InvalidOperationException("Select a speech model.");var custom=ModelDirectoryTextBox.Text.Trim();if(custom.Length==0&&!selected.Installed)throw new InvalidOperationException($"{selected.DisplayName} is not installed yet. Install it first.");var compute=(string?)ComputeComboBox.SelectedValue??"automatic";if(compute=="intel-gpu"&&(selected.Id!="small"||custom.Length>0))throw new InvalidOperationException("Intel GPU currently supports the managed Whisper Small model only. Select Whisper Small and clear the custom model directory.");if(compute=="intel-gpu"&&(LocalModelResolver.ResolveOpenVinoRuntime() is null||LocalModelResolver.ResolveOpenVinoSpeechModel("small") is null))throw new InvalidOperationException("Intel GPU is not ready. Install the OpenVINO runtime and Intel Whisper Small model first.");var value=new AppSettings(1,ScreenCaptureCheckBox.IsChecked==true,CaptureDirectoryTextBox.Text.Trim(),custom,compute,selected.Id);AppPreferences.Save(value);var storageRestart=value.CaptureDirectory!=_original.CaptureDirectory;MessageBox.Show(this,storageRestart?"Settings saved. Restart the application to apply the changed storage location.":"Settings saved. Model and compute changes apply immediately.","Settings",MessageBoxButton.OK,MessageBoxImage.Information);DialogResult=true;}catch(Exception exception){ResultText.Text=exception.Message;}}
    private sealed record Choice(string Label,string Value);
    private sealed record SpeechModelChoice(string Id,string DisplayName,string DirectoryName,string Quality,string DownloadSize,string HardwareGuidance,bool Installed){public SpeechModelChoice(LocalSpeechModelDefinition m,bool installed):this(m.Id,m.DisplayName,m.DirectoryName,m.Quality,m.DownloadSize,m.HardwareGuidance,installed){}public string InstallLabel=>Installed?"· Installed":"· Not installed";}
}
